  name: taide-cp
  channels:
    - nvidia/label/cuda-11.8.0
  dependencies:
    - python=3.10
    - pip
    - pytorch::pytorch
    - pytorch::pytorch-cuda=11.8
    - cuda
    - conda-forge::bash-completion
    - conda-forge::cmake
    - conda-forge::cxx-compiler
    - conda-forge::gcc=8
    - conda-forge::git-lfs
    - conda-forge::pkg-config
    - pip:
      - accelerate==0.25.0
      - datasets==2.15.0
      - deepspeed==0.12.5
      - fire
      - flash-attn==2.3.6
      - ipykernel
      - ipywidgets
      - jsonargparse[signatures]
      - lightning==2.1.2
      - omegaconf
      - optimum==1.16.1
      - peft==0.7.1
      - protobuf
      - safetensors
      - sentencepiece
      - tokenizers
      - transformers==4.36.2
      - wandb
      - -e ..
