seed_everything: 42
trainer:
  strategy: 
    class_path: EnhancedDeepSpeedStrategy
    init_args:
      stage: 3
      logging_level: 40 # logging.ERROR
  precision: 16-mixed
  logger:
    class_path: WandbLogger
    init_args:
      name: example
      save_dir: logs
      entity: tvllm
      project: Taide-CP
      save_code: true
  callbacks:
    - class_path: LearningRateMonitor
    - class_path: ModelCheckpoint
      init_args:
        save_on_train_epoch_end: true
        save_top_k: -1
    - class_path: ModelCheckpoint
      init_args:
        save_top_k: 1
        every_n_train_steps: 1000
    - class_path: ModelCheckpoint
      init_args:
        monitor: Perplexity/Val
        auto_insert_metric_name: false
        filename: epoch={epoch}-step={step}-ppl={Perplexity/Val:.2f}
  max_epochs: 1
  min_epochs: 1
  max_steps: -1
  min_steps: null
  val_check_interval: null
  check_val_every_n_epoch: null
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
model:
  class_path: LitLlamaForCausalLM
  init_args:
    config:
      model_path: <MODEL_PATH>
      tokenizer_path: <TOKENIZER_PATH>
      extend_vocab:
        pad_to_multiple_of: 8
      max_position_embeddings: 4096
      optimizer_config:
        lr: 1e-4
        betas:
          - 0.9
          - 0.95
        eps: 1e-5
        weight_decay: 1e-1
        lr_scheduler_type: cosine
        num_warmup_steps: 0
        min_lr_factor: 0.1
      patchers:
        - class_path: LLaMADeepSpeedPatcher
        # - class_path: LLaMAFP16Patcher
data:
  class_path: DataModuleForPreTraining
  init_args:
    config:
      dataset_kwargs:
        path: <DATASET_PATH>
      max_length: 4096
      stride: 2048
      concat_method: GROUP_BY_LENGTH
      pad_to_multiple_of: 8
      batch_size: 1
      num_proc: 32
      num_workers: 4
