seed_everything: 42
trainer:
  strategy: 
    class_path: taide_cp.lightning.DeepSpeedStrategy
    init_args:
      stage: 3
      logging_level: 40 # logging.ERROR
  precision: 16-mixed
  logger:
    class_path: WandbLogger
    init_args:
      name: llama2-13b|tokenizer=ccw|data=k>cc
      version: null
      save_dir: logs
      entity: tvllm
      project: Taide-CP
      tags: null
      notes: null
      group: null
      job_type: null
      save_code: true
  callbacks:
    - class_path: LearningRateMonitor
    - class_path: ModelCheckpoint
      init_args:
        save_on_train_epoch_end: true
        save_top_k: -1
    - class_path: ModelCheckpoint
      init_args:
        save_top_k: 1
        every_n_train_steps: 500
    - class_path: ModelCheckpoint
      init_args:
        monitor: Perplexity/Val
        auto_insert_metric_name: false
        filename: epoch={epoch}-step={step}-ppl={Perplexity/Val:.2f}
  max_epochs: 1
  min_epochs: 1
  max_steps: -1
  min_steps: null
  val_check_interval: 500
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  detect_anomaly: false
ckpt_path: null
model:
  class_path: LLaMAForPreTraining
  init_args:
    config:
      model_path: checkpoints/llama2-13b|tokenizer=ccw|data=k|epoch=0-step=13711
      tokenizer_path: checkpoints/tokenizer/llama-ccw
      max_position_embeddings: 4096
      extend_vocab: false
      optimizer_config:
        lr: 5e-5
        betas:
          - 0.9
          - 0.95
        eps: 1e-5
        weight_decay: 1e-1
        lr_scheduler_type: COSINE
        num_warmup_steps: 2000
        min_lr_factor: 0.1
    patchers:
      - class_path: LLaMADeepSpeedPatcher
      # - class_path: LLaMAFP16Patcher
data:
  class_path: DataModuleForPreTraining
  init_args:
    config:
      data_path: jed351/Traditional-Chinese-Common-Crawl-Filtered
      dataset_path: data/cp/tokenized/llama-ccw/cc
      max_length: 4096
      train_batch_size: 1
      val_batch_size: null
      val_split_size: 10000
      num_workers: 4
